### ISSUE TITLE
npm link fails for me

### ISSUE THREAD

**Issue by SudhindraKovalam** [graphistry/cljs#6]
I am no expert here. But when I try running "npm link" I get this error 

123@USLT1:~/Documents/Code/POCs/NodeJS/nodecljs/cljs|master
⇒  npm link

> node-opencl@0.3.0 install /Users/1/nodecljs/cljs/node_modules/node-opencl
> node-gyp rebuild --msvs_version=2013

  CXX(target) Release/obj.target/opencl/src/addon.o
In file included from ../src/addon.cpp:5:
In file included from ../src/event.h:5:
../src/nanextension.h:93:14: error: no member named 'SetIndexedPropertiesToExternalArrayData' in 'v8::Object'
     buffer->SetIndexedPropertiesToExternalArrayData(this->mPtr, v8::kExternalByteArray, (int) this->size);
     ~~~~~~  ^
../src/nanextension.h:93:70: error: no member named 'kExternalByteArray' in namespace 'v8'
     buffer->SetIndexedPropertiesToExternalArrayData(this->mPtr, v8::kExternalByteArray, (int) this->size);
                                                                 ~~~~^
2 errors generated.
make: *** [Release/obj.target/opencl/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--msvs_version=2013"
gyp ERR! cwd /Users/1/nodecljs/cljs/node_modules/node-opencl
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN cljs@0.0.1 No repository field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "link"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! node-opencl@0.3.0 install: `node-gyp rebuild --msvs_version=2013`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opencl@0.3.0 install script 'node-gyp rebuild --msvs_version=2013'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-opencl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --msvs_version=2013
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-opencl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-opencl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/1/nodecljs/cljs/npm-debug.log

Am I missing some prerequisites ?

**Comment by lmeyerov** [comment]
This sounds like `node-opencl` is failing. Can you try doing a vanilla install of node-opencl, e.g., `npm install node-opencl ; npm test`?

**Comment by SudhindraKovalam** [comment]
@lmeyerov tried the vanilla install of node-opencl 
still the same.

**Comment by thibaudh** [comment]
I see you are using node 5.8.0. The current master only works with node 0.10.X (yes that is old). Could you try the `node4` branch? It should work with node4 and probably node5 too.

**Comment by mateogianolio** [comment]
The `node4` branch works with node >=4.0.0 (just tried with 5.8.0).
